export type {
  BuiltIndexDefinition,
  CreateIndexBuilder,
  EntityConfig,
  EntityDefinition,
  EntityDeleteBuilder,
  EntityGetBuilder,
  EntityPutBuilder,
  EntityRepository,
  EntityUpdateBuilder,
  IndexBuilder,
  IndexDefinition,
  MappedQueries,
  PartitionKeyIndexBuilder,
  QueryEntity,
  QueryFunction,
  QueryFunctionWithSchema,
  QueryRecord,
} from "./entity/entity.js";
export { createIndex, createQueries, defineEntity } from "./entity/entity.js";
