name: Lint and Check Types for Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  install:
    name: Setting up dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Check types
        run: pnpm check-types

      - name: Run Unit tests
        run: pnpm test

      - name: Start DynamoDB Local
        run: |
          docker compose up -d dynamodb

      - name: Wait for DynamoDB
        run: |
          timeout=30
          while ! nc -z localhost 8897; do
            if [ $timeout -le 0 ]; then
              echo "DynamoDB failed to start"
              exit 1
            fi
            timeout=$((timeout-1))
            sleep 1
          done

      - name: Run Integration tests
        run: pnpm test:int
